### ISSUE TITLE
Major FPS Drops

### ISSUE THREAD

**Issue by LeiserGeist** [amadornes/Framez#23]
This could be a compatibility issue with another mod, I'm not 100% sure what's going on.

Mod Version 0.2-12, Minecraft Version 1.7.10, Forge version supplied in screenshots.

Attempting to power a frame structure with an RF motor drops my FPS to around 20.
Any size structure does it. As soon as I throw any RF power into it, the FPS tanks.

Before, normal FPS with vsync on:
![2015-01-06_13 22 31](https://cloud.githubusercontent.com/assets/2342807/5633656/8c087b5e-95a7-11e4-9d65-2cc163914f4b.png)

After applying power, tanked FPS:
![2015-01-06_13 22 46](https://cloud.githubusercontent.com/assets/2342807/5633687/c7f63dfe-95a7-11e4-8538-cd8ff73e11e5.png)

I don't need a new toaster, I have a modern rig
Any other info needed, I'll be happy to supply.

**Comment by amadornes** [comment]
The mod has been rewritten. This is now fixed :)
