### ISSUE TITLE
Not released

### ISSUE THREAD

**Issue by TheJulianJES** [amadornes/Framez#27]
Release the source D: <- Totally edited (not by me)

**Comment by rewbycraft** [comment]
+1

**Comment by amadornes** [comment]
Nah, keeping it closed is stupid. I'll just let people complain about it not being released yet here :P

**Comment by TheJulianJES** [comment]
The

**Comment by TheJulianJES** [comment]
Mod

**Comment by TheJulianJES** [comment]
Framez

**Comment by TheJulianJES** [comment]
2

**Comment by TheJulianJES** [comment]
is

**Comment by TheJulianJES** [comment]
still

**Comment by TheJulianJES** [comment]
not

**Comment by TheJulianJES** [comment]
released

**Comment by TheJulianJES** [comment]
.

**Comment by GirafiStudios** [comment]
Thanks for that spam Julian...

**Comment by TheJulianJES** [comment]
@GirafiStudios You're welcome!

**Comment by TheJulianJES** [comment]
This has no "Rewriting :3" label...

**Comment by modmuss50** [comment]
I am also experiencing this same issue. :P

**Comment by TheJulianJES** [comment]
New News: It will take even longer because the author adds "Connected" (yes, I know there is no "!") support.

**Comment by CubeWrench202** [comment]
This is funny :p, this issue is making me more exciting than before.

**Comment by TheJulianJES** [comment]
lol

**Comment by amadornes** [comment]
Heh, tends to happen :P

**Comment by dmodoomsirius** [comment]
https://github.com/amadornes/Framez/issues/29

**Comment by amadornes** [comment]
Thanks, @dmodoomsirius! Forgot to close it :)

**Comment by dmodoomsirius** [comment]
no prob @amadornes

**Comment by CubeWrench202** [comment]
I want frames....
_runs away_

**Comment by ghost** [comment]
Guy lets not rush Ama he needs to find the best way to break everything, we don't want him releasing something that works as it's meant to! ;)

**Comment by CubeWrench202** [comment]
I fully agree with you, if my game doesn't crashes whenever i place a frame, i will not use this mod anymore.

**Comment by amadornes** [comment]
We're almost there! :D

**Comment by TheJulianJES** [comment]
Woooooooo!

**Comment by modmuss50** [comment]
:)

**Comment by amadornes** [comment]
Fixed! :D
