### ISSUE TITLE
Crash when placing Flux Motor in FirePack

### ISSUE THREAD

**Issue by ThaDaVos** [amadornes/Framez#28]
The game crashes when ever I place the motor.
Here's my crash log: http://pastebin.com/tuhQKiYD

**Comment by TheJulianJES** [comment]
This is an issue from the "old Framez" which is no longer supported. You have to wait for Framez 2 which has many new features. ;)

(No guarantee)

**Comment by ThaDaVos** [comment]
Thanks for the quick answer.
When will Framez 2 to available for us to use?
Me and some friends are playing the FirePack and we would really like to mess with the frames but we can't use them atm

**Comment by TheJulianJES** [comment]
I don't know when it will come out but if you want you can join #Framez on esper.net (IRC) for the latest updates and news.

**Comment by amadornes** [comment]
The mod has been rewritten. This is now fixed :)
