### ISSUE TITLE
Crash on launch with BC

### ISSUE THREAD

**Issue by EwyBoy** [amadornes/Framez#31]
When I tired adding framez 2 version 2 0.1.1 and Trajectory 0.1.2 to my modpack I get a crash with the latest BC build 7.1.11. Here is the crash report: 

http://paste.ee/p/vU3Mt

**Comment by AEnterprise** [comment]
looks like framez isn't updated to the bc 7.1.x branch

**Comment by amadornes** [comment]
Ouch... I think I know what the issue is... If if is what I think it is, I'll push a fix for it in a couple of minutes

**Comment by amadornes** [comment]
Herp derp, forgot to include JTraits in the jar. The new file is waiting for approval on CF :)
